chatbot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('google_data/', include('google_data.urls')),
    path('kakao/', include('kakao.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

google_data/urls.py
from django.urls import path

from . import views

app_name = 'google_data'

urlpatterns = [
    # /google_data/
    path('', views.index, name='index'),
    # /google_data/activity/
    path('activity/', views.visualizeTopCountApp, name='visualizeTopCountApp'),
]

kakao/urls.py
from django.urls import path

from . import views

app_name = 'kakao'

urlpatterns = [
    # /kakao/
#    path('', views.IndexView.as_view(), name='index'),
    # /kakao/translate/
    path('translate/', views.translate, name='translate'),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    # /polls/
    path('', views.IndexView.as_view(), name='index'),
    # /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

google_data/models.py
from django.db import models

# Create your models here.

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

google_data/views.py
from django.shortcuts import render
from django.views import generic
from . import map
from . import android
import base64
from io import BytesIO

# Create your views here.

def index(request):
    text = ''
    return render(request, 'google_data/index.html', {'text':text})


# file upload test
def visualizeTopCountApp(request):
    text = ''
    if request.method == 'POST':
        count = request.POST['count']
        if count is not None and int(count) > 0:
            count = int(count)
        else:
            count = 10
        with request.FILES.get('activity_file') as fp:
            lh = android.AndroidDataHandler(fp=fp)
            service = android.AndroidService(lh)

        tmp = BytesIO()
        fig = service.visualizeTopCountApp(count)
        fig.savefig(tmp, format='png')
        encoded = base64.b64encode(tmp.getvalue()).decode('utf-8')
        text = '<img src=\'data:image/png;base64,{}\'>'.format(encoded)
    return render(request, 'google_data/index.html', {'text':text})

def visualizeLocation(request):
    text = ''
    if request.method == 'POST':
        target = request.POST['target']
        with request.FILES.get('location_file') as fp:
            lh = map.LocationDataHandler(fp=fp)
            service = map.MapService(lh)
        text = service.visualizeNearestLocation(target)._repr_html_()
    return render(request, 'google_data/index.html', {'text':text})

kakao/views.py
from django.shortcuts import render
from django.http import JsonResponse
from . import api, bot
import json

# Create your views here.


def translate(request):
    request_json = json.loads(request.body)
    request_text = request_json['action']['params']['text']
    response_text = api.kr_to_en(request_text)
    response_dict = bot.simpleText(response_text)
    return JsonResponse(response_dict)

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Question, Choice


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html',{
            'question' : question,
            'error_message' : "You didn't select a choice",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

quickstart/views.py
from django.shortcuts import render

# Create your views here.

google_data/templates/google_data/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'google_data/style.css' %}">


    <title>Google Data Visualization</title>
  </head>

  <body>

    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="./">Visualization</a>

    </nav>
      
      <div class="container-fluid">
        <div class="row">
          <nav class="col-md-2 d-none d-md-block bg-light sidebar">
            <div class="sidebar-sticky">
              <ul class="nav flex-column">
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    GeoData
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    Application
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    Search Word
                  </a>
                </li>
              </ul>
      
            </div>
          </nav>
      
          <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
              <h1 class="h2">Application</h1>
              <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group mr-2">
                  <button type="button" class="btn btn-sm btn-outline-secondary">상위N개</button>
                </div>
              </div>
            </div>
  
            <form action="{% url 'google_data:visualizeTopCountApp' %}" method="POST" enctype="multipart/form-data" class="form-horizontal" name="activity_file"> 
                {% csrf_token %}
                <div class="form-group">
                    <h3 class="h3">File</h3>

                    <div>
                        <h5 class="h6">안드로이드 활동내역 업로드 (HTML)</h5>
                        <input type="file" name="activity_file" id="activity_file" required="True" class="form-control btn btn-sm btn-outline-secondary">
                    </div>                    
                </div>


                <div class="form-group">
                
                    <div>
                        <h5 class="h6">상위 개수</h5>
                        <input type="text" name="count" id="count" required="True" class="form-control" placeholder="10">
                    </div>
                </div>
            

                <div class="form-group">                    
                    <div>
                        <button type="submit" class="btn btn-sm btn-outline-secondary">Upload</button>
                    </div> 
                </div>
            </form>
        

          </main>
        </div>
      </div>

      <div class="iframebox">
        {{ text | safe }}
      </div>
      
      
  </body>
</html>

google_data/templates/google_data/location.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'google_data/style.css' %}">


    <title>Google Data Visualization</title>
  </head>

  <body>

    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="./">Visualization</a>

    </nav>
      
      <div class="container-fluid">
        <div class="row">
          <nav class="col-md-2 d-none d-md-block bg-light sidebar">
            <div class="sidebar-sticky">
              <ul class="nav flex-column">
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    GeoData
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    Application
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    Search Word
                  </a>
                </li>
              </ul>
      
            </div>
          </nav>
      
          <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
              <h1 class="h2">Application</h1>
              <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group mr-2">
                  <button type="button" class="btn btn-sm btn-outline-secondary">상위N개</button>
                </div>
              </div>
            </div>
  
            <form action="{% url 'google_data:visualizeTopCountApp' %}" method="POST" enctype="multipart/form-data" class="form-horizontal" name="activity_file"> 
                {% csrf_token %}
                <div class="form-group">
                    <h3 class="h3">File</h3>

                    <div>
                        <h5 class="h6">안드로이드 활동내역 업로드 (HTML)</h5>
                        <input type="file" name="activity_file" id="activity_file" required="True" class="form-control btn btn-sm btn-outline-secondary">
                    </div>                    
                </div>


                <div class="form-group">
                
                    <div>
                        <h5 class="h6">상위 개수</h5>
                        <input type="text" name="count" id="count" required="True" class="form-control" placeholder="10">
                    </div>
                </div>
            

                <div class="form-group">                    
                    <div>
                        <button type="submit" class="btn btn-sm btn-outline-secondary">Upload</button>
                    </div> 
                </div>
            </form>
        

          </main>
        </div>
      </div>

      
    <div class="iframebox">
        {{ text | safe }}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

polls/templates/polls/detail.html
<h1> {{ question.question_text }} </h1>

{% if error_message %} <p><strong> {{error_message}} </strong></p> {% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id}}">
        <label for="choice{{ forloop.counter }}"> {{ choice.choice_text }} </label>
        <br>
    {% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
        
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">  {{ question.question_text }} </a></li>
        {% endfor %}
            
    </ul>
{% else %}
    <p>No Polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1> {{ question.question_text }} </h1>

<ul>
    
    {% for choice in question.choice_set.all %}
        <li>
            {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
        </li>
        
    {% endfor %}
        
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote Again?</a>